### ISSUE TITLE
do you have the starter files ??

### ISSUE THREAD

**Issue by marwanagdz** [cwhaley112/stanford-cs107#1]
Hi, 
I am doing a self-study for this course unfortunately I don't have starter files as you know I must be Stanford student.
do you have the starter files, I will be really appreciated ?

**Comment by whaleymar** [comment]
Hey! Unfortunately, I wasn't able to find starter code for a recent version of the course, but there *are* header files available for a (much) older version of the course here: https://see.stanford.edu/Course/CS107

The assignments aren't exactly the same as the course which I followed on YouTube but they're pretty close. For example, in the old course it has you implement a hashset, while in the newer version you build a hashmap. I changed my header file for that assignment to work with a hashmap so feel free to use that :)

For the binary bomb lab, you can find some binaries floating around on github (or use the one in this repo). 

Hopefully this helps!
